core/models.py
__author__ = 'mrlaolu'
__description__ = 'managing other tables'

import datetime   

from core import db, app
from core.utils import slugify

config = app.config

class ContactUs(db.Model):

    __tablename__='contactus'

    id=db.Column(db.Integer, primary_key=True)
    sender=db.Column(db.String(120))
    email=db.Column(db.String(245))
    phone=db.Column(db.String(120))
    note=db.Column(db.String(255))
    sent_at = db.Column(db.DateTime, default=db.func.now())
    sender_ip = db.Column(db.String(15))
    last_browser = db.Column(db.String(254))
    read = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, sender, email, note, sender_ip):
        self.sender=sender
        self.email=email
        #self.phone=phone
        self.note=note
        self.sender_ip=sender_ip

    def __repr__(self):
        return '<Contact Us %r>' % (self.sender)

class Country(db.Model):
    """
    A location where humans are listed, using geoid for primary key.
    """    
    __tablename__='countries'

    id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(30))
    code=db.Column(db.String(5))
    phone=db.Column(db.String(10))
    slug=db.Column(db.String(120))
    icon=db.Column(db.String(120)) 
    users=db.relationship('Profile', backref='countries', lazy='dynamic') 

    def __init__(self, id, code, name, phone):
        self.id=id
        self.code=code
        self.name=name
        self.phone=phone
        self.slug=slugify(self.name)

    def __repr__(self):
        return '<Country %r>' % (self.name)

    def count_cities(self):
        rs=self.city
        return rs.count()

core/pages/forms.py
# -*- coding: utf-8 -*-

"""
"""
import re
from flask.ext.wtf import Form
from wtforms import (
    StringField, TextAreaField, 
    PasswordField, BooleanField, 
    FileField, SelectField, RadioField
)
from wtforms.validators import Required, EqualTo, Email, URL, Length

class ContactForm(Form):
    sender = StringField('Full Name', [Required()])
    email = StringField('Email address', [Required(), Email()])
    school = StringField('School', [Required()])
    phone = StringField('Phone Number', [Required()])
    note = TextAreaField('Note', [Required()])

core/__init__.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
VERSION = (0, 1, 0)

__version__ = ".".join(map(str, VERSION))
__status__ = "Ready"
__description__ = "Boompi"
__author__ = "Laolu Akindolire <mrlaolu@gmx.com>"
__license__ = "Proprietary Software"
__copyright__ = "Copyright 2017, Kindo Labs"


###########
# imports #
###########
import os
import os.path as op
from datetime import datetime
from flask import Flask, render_template, abort, \
request, url_for, redirect, send_from_directory, json, Response
from werkzeug.routing import BaseConverter

from flask_security import Security, SQLAlchemyUserDatastore, \
UserMixin, RoleMixin, login_required, current_user
from flask_security.utils import encrypt_password

from flask.ext.mail import Mail
from flask.ext.login import LoginManager
from flask.ext.sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CsrfProtect

from sqlalchemy import func

from core.momentjs import momentjs

import flask_admin as myadmin
from flask_admin import Admin 
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_admin import helpers as admin_helpers

##########
# config #
##########

app = Flask(__name__)
#env = os.environ.get('APP_ENV')

config = app.config

#config.from_object('config.%sConfig' % env.capitalize())

# for MS windows only 
env = 'development'
config.from_object('config.%sConfig' % env.capitalize())

app.jinja_env.globals['momentjs'] = momentjs


##############
# extensions # 
##############

db = SQLAlchemy(app)
csrf= CsrfProtect(app)
mail = Mail(app)

@app.template_filter()
def copyyear():
    value=datetime.now()
    return value.strftime('%y')

@app.template_filter()
def blogdatetime(value, format='%d %b, %Y at %I:%M %p'):
    """convert a datetime to a different format."""
    return value.strftime(format)
    
@app.template_filter('formatdate')
def format_datetime_filter(input_value, format_="%a, %d %b %Y"):
    return input_value.strftime(format_)

@app.template_filter()
def currency(amount):
    currency = config['CURRENCY']
    currency_code = currency['NGN']['symbol']
    return '{}{:,.0f}'.format(currency_code, amount)






from core.models import *
from core.users.models import *
from core.tracks.models import *


# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)


##############
# blueprints #
##############

from core.users.views import mod as base_module
app.register_blueprint(base_module)

from core.home.views import mod as base_module
app.register_blueprint(base_module)

from core.tracks.views import mod as base_module
app.register_blueprint(base_module)

from core.pages.views import mod as base_module
app.register_blueprint(base_module)


from core.ajax import mod as base_module
app.register_blueprint(base_module)


# Setup Flask-Admin
admin = Admin(
    app,
    name='Dashboard',
    url='/dashboard/1111',
    base_template='admin/my_master.html', template_mode='bootstrap3'
)

from wtforms.fields import PasswordField

# Custom model view class
class BaseMV(ModelView):

    def is_accessible(self):
        if not current_user.is_active or not current_user.is_authenticated:
            return False

        return current_user.has_role('admin') or current_user.has_role('moderator')

    def _handle_view(self, name, **kwargs):
        """
        Override builtin _handle_view in order to redirect users when a view is not accessible.
        """
        if not self.is_accessible():
            if current_user.is_authenticated:
                # permission denied
                abort(403)
            else:
                # login
                return redirect(url_for('home.login', next=request.url))


class UserMV(BaseMV):
    # Don't display the password on the list of Users
    #column_exclude_list = ('password','salt','reset_password_token','confirmation_token','confirmed_on', 'username')

    #column_searchable_list = ('fullname')

    # Don't include the standard password field when creating or editing a User (but see below)
    #form_excluded_columns = column_exclude_list

    # Automatically display human-readable names for the current and available Roles when creating or editing a User
    column_auto_select_related = True

    # On the form for creating or editing a User, don't display a field corresponding to the model's password field.
    # There are two reasons for this. First, we want to encrypt the password before storing in the database. Second,
    # we want to use a password field (with the input masked) rather than a regular text field.
    def scaffold_form(self):

        # Start with the standard form as provided by Flask-Admin. We've already told Flask-Admin to exclude the
        # password field from this form.
        form_class = super(UserMV, self).scaffold_form()

        # Add a password field, naming it "password2" and labeling it "New Password".
        form_class.password2 = PasswordField('New Password')
        return form_class

    # This callback executes when the user saves changes to a newly-created or edited User -- before the changes are
    # committed to the database.
    def on_model_change(self, form, model, is_created):

        # If the password field isn't blank...
        if len(model.password2):

            # ... then encrypt the new password prior to storing it in the database. If the password field is blank,
            # the existing password in the database will be retained.
            model.password = generate_password_hash(model.password2)

# Customized Role model for SQL-Admin
class RoleAdmin(ModelView):

    # Prevent administration of Roles unless the currently logged-in user has the "admin" role
    def is_accessible(self):
        return current_user.has_role('admin')



'''
class JobMV(BaseMV):
    column_searchable_list = ('title',)

class JobMainMV(BaseMV):
    column_exclude_list = ('cv_required',)



#admin.add_view(AnalyticsView(name='Analytics', endpoint='analytics'))
# Add administrative views here
admin.add_view(UserMV(User, db.session))
admin.add_view(RoleAdmin(Role, db.session))


admin.add_view(JobMainMV(Job, db.session))
admin.add_view(JobMV(JobCategory, db.session))
admin.add_view(JobMV(JobSubCategory, db.session))
admin.add_view(BaseMV(JobRequest, db.session))
admin.add_view(BaseMV(Country, db.session))
admin.add_view(BaseMV(ContactUs, db.session))'''


# define a context processor for merging flask-admin's template context into the
# flask-security views.
@security.context_processor
def security_context_processor():
    return dict(
        admin_base_template=admin.base_template,
        admin_view=admin.index_view,
        h=admin_helpers,
        get_url=url_for
    )


##################
# Robots.txt and Sitemap.xml #
##################
@app.route('/robots.txt')
@app.route('/sitemap.xml')
@app.route('/opensearch.xml')
def static_from_root():
    return send_from_directory(app.static_folder, request.path[1:])



##################
# error handlers #
##################

@app.errorhandler(404)
def error_404(error):
    return render_template('error/404.html', title = 'Oops!'), 404

@app.errorhandler(500)
def error_500(error):
    return render_template('error/500.html', title = 'Server Screwed'), 500

core/home/__init__.py
# -*- coding: utf-8 -*-

core/home/views.py
# -*- coding: utf-8 -*-

import logging
import datetime
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for, json, Response)
from werkzeug import check_password_hash, generate_password_hash
from core.token import generate_confirmation_token, confirm_token

from core import app
from core import db

from core.users.forms import *
from flask_security import login_required, current_user

config = app.config

mod = Blueprint('home', __name__, url_prefix='')

@app.before_request
def before_request():
    from core.users.models import User
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route(r'/')
def index():
  # main page

  return render_template(
    'home.html', title = 'Find and Browse Music on %s ' %(config['BRAND']),\
    bdy_class = 'home', user=g.user,
    landing_pg=True
  )

@mod.route(r'/auth/login', methods=['GET', 'POST'])
def login():
  if g.user:
    return redirect(url_for('home.index'))

  next = ''
  if request.method == 'GET':
      if 'next' in request.args:
          next = request.args['next']

  form = LoginForm(request.form)

  return render_template('auth/signin.html', \
    title = 'Log In', form=form, next=next, bdy_class='auth')

@mod.route(r'/auth/forgot', methods=['GET', 'POST'])
def forgot():
  if g.user:
    return redirect(url_for('home.index'))

  next = ''
  if request.method == 'GET':
      if 'next' in request.args:
          next = request.args['next']

  form = LoginForm(request.form)

  return render_template('auth/forgot.html', \
    title = 'Forgot Password', form=form, next=next, bdy_class='auth')

@mod.route(r'/auth/signup', methods=['GET', 'POST'])
def register():
  if g.user:
    return redirect(url_for('home.index'))

  next = ''
  if request.method == 'GET':
      if 'next' in request.args:
          next = request.args['next']

  form = RegisterForm(request.form)

  return render_template('auth/signup.html', \
    form=form, title = 'Sign Up', next=next, bdy_class='auth')

@mod.route(r'/auth/logout', methods=['GET', 'POST'])
@login_required
def logout():
  session.pop('user_id', None)
  flash('Successfully logged out')
  return redirect(url_for('home.index'))



@mod.route(r'/account/verify/<token>', methods=['GET', 'POST'])
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The verification link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already verified. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmation_token = token
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have verified your account. Thanks!', 'success')
    return redirect(url_for('home.index'))

core/pages/__init__.py
# -*- coding: utf-8 -*-

core/pages/views.py
# -*- coding: utf-8 -*-

import logging
import datetime
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for, json, Response)
from werkzeug import check_password_hash, generate_password_hash

from core import app
from core import db

from core.pages.forms import ContactForm
from flask.ext.login import login_user, logout_user, \
      login_required, current_user


mod = Blueprint('pages', __name__, url_prefix='')

#globals
logging.basicConfig(level=logging.INFO)
logging.basicConfig(format='%(message)s', level=logging.INFO)


@app.before_request
def before_request():
    from core.users.models import User
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

"""
Content
"""

@mod.route('/about')
def about():
    return render_template('company/about.html', title='About', bdy_class='content', user=g.user)

@mod.route('/how-it-works')
def how_it_works():
    form = ContactForm(request.form)
    return render_template('company/how-it-works.html', title='About', bdy_class='content', form=form, user=g.user)

@mod.route('/contact-us')
def contact_us():
    form = ContactForm(request.form)
    return render_template('company/contact.html', title='About', bdy_class='content', form=form, user=g.user)

@mod.route('/terms-of-service')
def terms():
    return render_template('company/terms.html', title='Terms of Service', bdy_class='content', user=g.user)

@mod.route('/privacy-policy')
def privacy():
    return render_template('company/privacy.html', title='Privacy Policy', bdy_class='content', user=g.user)

core/templates/footer.html
<footer class="footer" itemscope="" itemtype="http://schema.org/Organization">

                <!-- <div class="footer-top">

                </div> -->
                <div class="footer-top">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-10">
                                <ul>
                                    <li class="footer-language">
                                        <a href="{{ url_for('pages.about') }}"> About</a>
                                    </li>
                                    <li class="footer-language">
                                        <a href="{{ url_for('pages.privacy') }}"> Privacy Policy</a>
                                    </li>
                                    <li class="footer-language">
                                        <a href="{{ url_for('pages.terms') }}"> Terms of Use</a>
                                    </li>
                                    <li class="footer-language">
                                        <a href=""> Submit a New Song</a>
                                    </li>

                                    -&nbsp;Follow:
                                    <li class="footer-language">
                                        <a href=""> <strong>Twitter</strong></a>
                                    </li>
                                    <li class="footer-language">
                                        <a href=""> <strong>Facebook</strong></a>
                                    </li>
                                </ul>
                            </div>

                            <div class="logo col-xs-2"></div>

                            <div class="footer-legal col-xs-12">
                                <ul>
                                    <li>&copy; 2017 <span itemprop="name">{{config.BRAND}}</span>. All rights reserved</li>
                                </ul>

                                <!-- wir nicht resp. für media -->
                                <p class="footer-legal-wiki">
                                    {{config.BRAND}} is not responsible for all audio-visuals uploaded onto this platform.
                                </p>


                            </div>
                        </div>
                    </div>
                </div>

            </footer>

core/templates/google_tag_code.html
<!--Google Analytics-->
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXX-1', 'auto');
  ga('send', 'pageview');

</script>

<!--End Google analytics-->

core/templates/home.html
{% extends "layout.html" %}

{% block hero_slider %} <div class="hero-slider" id="js-featured-hm-carols"></div> {% endblock %}

{% block content_top %}
    <div class="content-top-inner-wrap">
        <div class="container content-top-lower">
            <h1 class="content-top-header"> Top 50 Gospel Music</h1>
            <nav class="navlist secondary-nav navlist--more" aria-label="Secondary navigation" data-require="components/collapsing-nav" data-more-string="More…">
                <ul class="navlist-items" id="js-navlist-genre-items" style="position: relative;">
                </ul>
                <div class="navlist-more-wrap"><button aria-expanded="false" aria-controls="d27471d0-49b3-4340-860c-2f86afbbee59" data-disclose-collapsing-nav="true" class="navlist-more navlist-more--hidden">More…</button>
                    <ul class="disclose-hide navlist-hidden-list" id="d27471d0-49b3-4340-860c-2f86afbbee59">
                        <li style="display: none;">
                            <a href="">Gospel Charts<span>(current section)</span></a>
                        </li>
                        <li style="display: none;">
                            <a href="s">Nigeria</a>
                        </li>
                        <li style="display: none;">
                            <a href="">Ghanaian</a>
                        </li>
                        <li style="display: none;">
                            <a href="">America</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
{% endblock %}

{% block body %}



<nav class="music-nav hide">
                        <p class="music-nav-description">Jump to:</p>
                        <ul class="music-nav-items">
                            <li class="music-nav-item music-nav-item--mobile"><a href="/music#top-artists">Top Artists</a></li>
                            <li class="music-nav-item"><a href="/music#top-releases">Top New Releases</a></li>
                            <li class="music-nav-item"><a href="/music#most-loved">Most Loved</a></li>
                        </ul>
                    </nav>

                    <section class="music-charts">

                        <div class="music-charts-row">
                            <div class="music-charts-col">
                                <header>
                                    <a id="top-tracks" class="offset-section-anchor"></a>
                                    <h2 class="buffer-reset"><span>Popular</span> Tracks</h2>
                                </header>
                                <table class="globalchart" style="background-image: url({{ url_for('static', filename='uploads/270463-300x300.jpg') }});">
                                    <thead class="sr-only">
                                        <tr>
                                            <th>Rank</th>
                                            <th>Cover</th>
                                            <th>Track name</th>
                                            <th>Artiste name</th>
                                            <th>Listeners</th>
                                        </tr>
                                    </thead>
                                    <tbody id="js-ready-tracks">

                                    </tbody>
                                </table>

                            </div>
                            <div class="music-charts-col">
                                <header>
                                    <a id="top-artists" class="offset-section-anchor"></a>
                                    <h2 class="buffer-reset"><span>Ranking</span> Artistes</h2>
                                </header>
                                <table class="globalchart" style="background-image: url({{ url_for('static', filename='uploads/tr657.jpg') }});">
                                    <thead class="sr-only">
                                        <tr>
                                            <th>Rank</th>
                                            <th>Avatar</th>
                                            <th>Artist name</th>
                                            <th>Listeners</th>
                                        </tr>
                                    </thead>
                                    <tbody id="js-ready-artistes">

                                    </tbody>
                                </table>



                            </div>
                        </div>

                    </section>

{% endblock %}

core/templates/nav_bar.html
<nav class="masthead">
                <div class="masthead-inner-wrap">
                    <span class="masthead-logo">
                        <!--span class="masthead-logo-loading"></span-->
                        <a href="{{ url_for('home.index') }}"> {{config.BRAND}}</a>
                    </span>

                    <a class="masthead-search-toggle" href="https://www.boompi.com/search" id="js-masthead-nav-search-button">Search</a>

                    <form class="masthead-search-form disclose-hide" id="masthead-search" action="https://www.boompi.com/search" method="get">
                        <div class="masthead-search-inner-wrap"><label for="masthead-search-field" class="sr-only">Search</label><input id="masthead-search-field" class="masthead-search-field" type="text" name="q" placeholder="Search for music…"><button class="masthead-search-submit" type="submit">Search</button></div>
                    </form>

                    <div class="visible-xs">
                        <button class="masthead-hamburger-toggle" id="js-masthead-nav-button">Toggle navigation</button>
                        <ul class="masthead-nav disclose-hide" id="masthead-nav">
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="{{ url_for('home.index') }}" data-analytics-action="NavigationLink" data-analytics-label="live">Top 50</a></li>
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="/music" data-analytics-action="NavigationLink" data-analytics-label="music">Features</a></li>
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="/events" data-analytics-action="NavigationLink" data-analytics-label="events">Artistes</a></li>
                            {% if not current_user.is_authenticated %}
                            <li class="masthead-nav-item">
                                <a class="masthead-nav-control" href="{{ url_for('home.register') }}" data-analytics-action="SignUpClick">Join</a>
                            </li>
                            <li class="masthead-nav-item">
                                <a class="masthead-nav-control" href="{{ url_for('home.login') }}">Login</a>
                            </li>
                            {% endif %}
                          {% if current_user.is_authenticated %}
                            {% if current_user and current_user.has_role('admin') or current_user.has_role('moderator') %}<li><a href="{{ url_for('admin.index') }}"><i class="icon icon-edit"></i>Dashboard</a></li>{% endif %}
                            <li><a href="{{ url_for('home.logout') }}"><i class="icon icon-logout"></i>Log Out</a></li>
                          {% endif %}
                        </ul>
                    </div>

                    <div class="navlist navlist--more masthead-nav hidden-xs" data-require="components/primary-nav" data-more-string="More…">
                        <ul class="js-navlist-items navlist-items" aria-label="Primary navigation" style="position: relative;">
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="{{ url_for('home.index') }}" data-analytics-action="NavigationLink" data-analytics-label="live">Top 50</a></li>
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="/music" data-analytics-action="NavigationLink" data-analytics-label="music">Features</a></li>
                            <li class="masthead-nav-item"><a class="masthead-nav-control" href="/events" data-analytics-action="NavigationLink" data-analytics-label="events">Artistes</a></li>
                        </ul>
                        <div class="navlist-more-wrap"><button aria-expanded="false" aria-controls="bb6c8e14-a384-401c-9fd0-ce328b7232ee" data-disclose-collapsing-nav="true" class="navlist-more navlist-more--hidden">More…</button>
                            <ul aria-label="Primary navigation" class="disclose-hide navlist-hidden-list" id="bb6c8e14-a384-401c-9fd0-ce328b7232ee">
                                <li style="display: none;"><a href="{{ url_for('home.index') }}" data-analytics-action="NavigationLink" data-analytics-label="live">Live</a></li>
                                <li style="display: none;"><a href="/music" data-analytics-action="NavigationLink" data-analytics-label="music">Music</a></li>
                                <li style="display: none;"><a href="/events" data-analytics-action="NavigationLink" data-analytics-label="events">Events</a></li>
                                <li style="display: none;"><a href="/features" data-analytics-action="NavigationLink" data-analytics-label="features">Features</a></li>
                            </ul>
                        </div>
                    </div>
                    {% if not current_user.is_authenticated %}
                    <ul class=" site-auth site-auth--anon hidden-xs ">
                        <li class="site-auth-item"><a class="site-auth-control" href="{{ url_for('home.register') }}" data-analytics-action="SignUpClick">Join</a></li>
                        <li class="site-auth-item"><a class="site-auth-control" href="{{ url_for('home.login') }}">Login</a></li>
                    </ul>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                            {% if current_user and current_user.has_role('admin') or current_user.has_role('moderator') %}<li><a href="{{ url_for('admin.index') }}"><i class="icon icon-edit"></i>Dashboard</a></li>{% endif %}
                            <li><a href="{{ url_for('home.logout') }}"><i class="icon icon-logout"></i>Log Out</a></li>
                    {% endif %}
                </div>
            </nav>

core/templates/right_side_bar.html
{%- if adbanner %} <div id="ad-banner-sm" style="min-height: 50px"></div> {% endif -%}
<section class="news-flash">
    <header>
        <h2><span>Boompi</span> News</h2>
        <!--h2 class="sidebar-group-heading">
                                        7 Jul 2017 — 13 Jul 2017
                                    </h2-->
    </header>
    <ol class="album-grid album-grid--releases" id="js-ready-nachrichten"></ol>

    <p class="more-link">
        <a href="">More news</a>
    </p>
</section>

core/templates/top_nav_bar.html
<div class="top-bar">

        <section class="player-bar inactive" aria-label="audio player" aria-disabled="true">
            <div class="player-bar-inner-wrap">
                {#<a class="player-bar-artwork js-artwork">
                    <img class="" src="{{ url_for('static', filename='images/_player_default_album.png') }}" alt="">
                </a>#}

                <div class="player-bar-now-playing">
                    <div class="player-bar-now-playing-inner-wrap">
                        {#<!-- <p class="player-bar-track js-player-status" aria-label="now playing" aria-live="polite" aria-atomic="true">
                            Loading player…
                        </p> -->#}
                        <p><i>...music that heals the soul</i></p>

                        {#<p class="player-bar-error js-player-error player-bar-status--hide">
                            <span class="player-bar-error-message js-player-error-message"></span>
                        </p>#}
                    </div>
                </div>
            </div>


            {#<div class="player-bar-progress-wrap">
                <div class="player-bar-progress" aria-label="progress" role="timer">
                    <div class="
                        js-progress-slug
                        player-bar-progress-slug
                    ">
                        <span class="
                            js-progress-remaining
                            player-bar-progress-remaining
                        " aria-label="remaining"></span>
                    </div>
                </div>
            </div>

            <div data-require="player/scrobble-client"></div>#}
        </section>



    </div>